//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevWebApi.MGIWebservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MGIWebservice.MGISoap")]
    public interface MGISoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidationRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DevWebApi.MGIWebservice.ValidationResponse ValidationRequest(DevWebApi.MGIWebservice.ValidationRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidationRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<DevWebApi.MGIWebservice.ValidationResponse> ValidationRequestAsync(DevWebApi.MGIWebservice.ValidationRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DevWebApi.MGIWebservice.LoadResponse LoadRequest(DevWebApi.MGIWebservice.LoadRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<DevWebApi.MGIWebservice.LoadResponse> LoadRequestAsync(DevWebApi.MGIWebservice.LoadRequest Request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.moneygram.com/RealTimeEP")]
    public partial class ValidationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime processDateTimeField;
        
        private string receiveAgentIdField;
        
        private string receiveCodeField;
        
        private string receiveISOCurrencyField;
        
        private string receiveISOCountryField;
        
        private string receiveAccountNumberField;
        
        private string sendISOCurrencyField;
        
        private string sendISOCountryField;
        
        private System.Nullable<decimal> sendFxRateField;
        
        private bool sendFxRateFieldSpecified;
        
        private decimal sendAmountField;
        
        private System.Nullable<decimal> feeAmountField;
        
        private bool feeAmountFieldSpecified;
        
        private decimal receiveAmountField;
        
        private string senderFirstNameField;
        
        private string senderMiddleNameField;
        
        private string senderLastNameField;
        
        private string senderAddress1Field;
        
        private string senderAddress2Field;
        
        private string senderCityField;
        
        private string senderStateProvinceField;
        
        private string senderCountryField;
        
        private string senderZipPostalCodeField;
        
        private string senderPhoneNumberField;
        
        private string senderDateOfBirthField;
        
        private string senderPhotoIdTypeField;
        
        private string senderPhotoIdNumberField;
        
        private string senderPhotoIdStateProvinceField;
        
        private string senderPhotoIdCountryField;
        
        private string senderLegalIdTypeField;
        
        private string senderLegalIdNumberField;
        
        private string receiverFirstNameField;
        
        private string receiverMiddleNameField;
        
        private string receiverLastNameField;
        
        private string receiveAccountNumberExpStrField;
        
        private System.Nullable<bool> receiveAccountSwipeField;
        
        private bool receiveAccountSwipeFieldSpecified;
        
        private string purposeOfFundsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime processDateTime {
            get {
                return this.processDateTimeField;
            }
            set {
                this.processDateTimeField = value;
                this.RaisePropertyChanged("processDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string receiveAgentId {
            get {
                return this.receiveAgentIdField;
            }
            set {
                this.receiveAgentIdField = value;
                this.RaisePropertyChanged("receiveAgentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string receiveCode {
            get {
                return this.receiveCodeField;
            }
            set {
                this.receiveCodeField = value;
                this.RaisePropertyChanged("receiveCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string receiveISOCurrency {
            get {
                return this.receiveISOCurrencyField;
            }
            set {
                this.receiveISOCurrencyField = value;
                this.RaisePropertyChanged("receiveISOCurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string receiveISOCountry {
            get {
                return this.receiveISOCountryField;
            }
            set {
                this.receiveISOCountryField = value;
                this.RaisePropertyChanged("receiveISOCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string receiveAccountNumber {
            get {
                return this.receiveAccountNumberField;
            }
            set {
                this.receiveAccountNumberField = value;
                this.RaisePropertyChanged("receiveAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string sendISOCurrency {
            get {
                return this.sendISOCurrencyField;
            }
            set {
                this.sendISOCurrencyField = value;
                this.RaisePropertyChanged("sendISOCurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string sendISOCountry {
            get {
                return this.sendISOCountryField;
            }
            set {
                this.sendISOCountryField = value;
                this.RaisePropertyChanged("sendISOCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<decimal> sendFxRate {
            get {
                return this.sendFxRateField;
            }
            set {
                this.sendFxRateField = value;
                this.RaisePropertyChanged("sendFxRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sendFxRateSpecified {
            get {
                return this.sendFxRateFieldSpecified;
            }
            set {
                this.sendFxRateFieldSpecified = value;
                this.RaisePropertyChanged("sendFxRateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal sendAmount {
            get {
                return this.sendAmountField;
            }
            set {
                this.sendAmountField = value;
                this.RaisePropertyChanged("sendAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<decimal> feeAmount {
            get {
                return this.feeAmountField;
            }
            set {
                this.feeAmountField = value;
                this.RaisePropertyChanged("feeAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool feeAmountSpecified {
            get {
                return this.feeAmountFieldSpecified;
            }
            set {
                this.feeAmountFieldSpecified = value;
                this.RaisePropertyChanged("feeAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public decimal receiveAmount {
            get {
                return this.receiveAmountField;
            }
            set {
                this.receiveAmountField = value;
                this.RaisePropertyChanged("receiveAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string senderFirstName {
            get {
                return this.senderFirstNameField;
            }
            set {
                this.senderFirstNameField = value;
                this.RaisePropertyChanged("senderFirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string senderMiddleName {
            get {
                return this.senderMiddleNameField;
            }
            set {
                this.senderMiddleNameField = value;
                this.RaisePropertyChanged("senderMiddleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string senderLastName {
            get {
                return this.senderLastNameField;
            }
            set {
                this.senderLastNameField = value;
                this.RaisePropertyChanged("senderLastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string senderAddress1 {
            get {
                return this.senderAddress1Field;
            }
            set {
                this.senderAddress1Field = value;
                this.RaisePropertyChanged("senderAddress1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string senderAddress2 {
            get {
                return this.senderAddress2Field;
            }
            set {
                this.senderAddress2Field = value;
                this.RaisePropertyChanged("senderAddress2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string senderCity {
            get {
                return this.senderCityField;
            }
            set {
                this.senderCityField = value;
                this.RaisePropertyChanged("senderCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string senderStateProvince {
            get {
                return this.senderStateProvinceField;
            }
            set {
                this.senderStateProvinceField = value;
                this.RaisePropertyChanged("senderStateProvince");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string senderCountry {
            get {
                return this.senderCountryField;
            }
            set {
                this.senderCountryField = value;
                this.RaisePropertyChanged("senderCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string senderZipPostalCode {
            get {
                return this.senderZipPostalCodeField;
            }
            set {
                this.senderZipPostalCodeField = value;
                this.RaisePropertyChanged("senderZipPostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string senderPhoneNumber {
            get {
                return this.senderPhoneNumberField;
            }
            set {
                this.senderPhoneNumberField = value;
                this.RaisePropertyChanged("senderPhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public string senderDateOfBirth {
            get {
                return this.senderDateOfBirthField;
            }
            set {
                this.senderDateOfBirthField = value;
                this.RaisePropertyChanged("senderDateOfBirth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public string senderPhotoIdType {
            get {
                return this.senderPhotoIdTypeField;
            }
            set {
                this.senderPhotoIdTypeField = value;
                this.RaisePropertyChanged("senderPhotoIdType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public string senderPhotoIdNumber {
            get {
                return this.senderPhotoIdNumberField;
            }
            set {
                this.senderPhotoIdNumberField = value;
                this.RaisePropertyChanged("senderPhotoIdNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public string senderPhotoIdStateProvince {
            get {
                return this.senderPhotoIdStateProvinceField;
            }
            set {
                this.senderPhotoIdStateProvinceField = value;
                this.RaisePropertyChanged("senderPhotoIdStateProvince");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public string senderPhotoIdCountry {
            get {
                return this.senderPhotoIdCountryField;
            }
            set {
                this.senderPhotoIdCountryField = value;
                this.RaisePropertyChanged("senderPhotoIdCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public string senderLegalIdType {
            get {
                return this.senderLegalIdTypeField;
            }
            set {
                this.senderLegalIdTypeField = value;
                this.RaisePropertyChanged("senderLegalIdType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public string senderLegalIdNumber {
            get {
                return this.senderLegalIdNumberField;
            }
            set {
                this.senderLegalIdNumberField = value;
                this.RaisePropertyChanged("senderLegalIdNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public string receiverFirstName {
            get {
                return this.receiverFirstNameField;
            }
            set {
                this.receiverFirstNameField = value;
                this.RaisePropertyChanged("receiverFirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public string receiverMiddleName {
            get {
                return this.receiverMiddleNameField;
            }
            set {
                this.receiverMiddleNameField = value;
                this.RaisePropertyChanged("receiverMiddleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public string receiverLastName {
            get {
                return this.receiverLastNameField;
            }
            set {
                this.receiverLastNameField = value;
                this.RaisePropertyChanged("receiverLastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public string receiveAccountNumberExpStr {
            get {
                return this.receiveAccountNumberExpStrField;
            }
            set {
                this.receiveAccountNumberExpStrField = value;
                this.RaisePropertyChanged("receiveAccountNumberExpStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public System.Nullable<bool> receiveAccountSwipe {
            get {
                return this.receiveAccountSwipeField;
            }
            set {
                this.receiveAccountSwipeField = value;
                this.RaisePropertyChanged("receiveAccountSwipe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool receiveAccountSwipeSpecified {
            get {
                return this.receiveAccountSwipeFieldSpecified;
            }
            set {
                this.receiveAccountSwipeFieldSpecified = value;
                this.RaisePropertyChanged("receiveAccountSwipeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=34)]
        public string purposeOfFunds {
            get {
                return this.purposeOfFundsField;
            }
            set {
                this.purposeOfFundsField = value;
                this.RaisePropertyChanged("purposeOfFunds");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.moneygram.com/RealTimeEP")]
    public partial class LoadResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ValidType validField;
        
        private string partnerTransactionIDField;
        
        private string mgiErrorCodeField;
        
        private string[] customErrorParamsField;
        
        private string receiptCodeField;
        
        private string[] customReceiptParamsField;
        
        private string bpgErrorCodeField;
        
        private string partnerErrorCodeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ValidType valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
                this.RaisePropertyChanged("valid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string partnerTransactionID {
            get {
                return this.partnerTransactionIDField;
            }
            set {
                this.partnerTransactionIDField = value;
                this.RaisePropertyChanged("partnerTransactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string mgiErrorCode {
            get {
                return this.mgiErrorCodeField;
            }
            set {
                this.mgiErrorCodeField = value;
                this.RaisePropertyChanged("mgiErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("customErrorParams", IsNullable=true, Order=3)]
        public string[] customErrorParams {
            get {
                return this.customErrorParamsField;
            }
            set {
                this.customErrorParamsField = value;
                this.RaisePropertyChanged("customErrorParams");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string receiptCode {
            get {
                return this.receiptCodeField;
            }
            set {
                this.receiptCodeField = value;
                this.RaisePropertyChanged("receiptCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("customReceiptParams", IsNullable=true, Order=5)]
        public string[] customReceiptParams {
            get {
                return this.customReceiptParamsField;
            }
            set {
                this.customReceiptParamsField = value;
                this.RaisePropertyChanged("customReceiptParams");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string bpgErrorCode {
            get {
                return this.bpgErrorCodeField;
            }
            set {
                this.bpgErrorCodeField = value;
                this.RaisePropertyChanged("bpgErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string partnerErrorCode {
            get {
                return this.partnerErrorCodeField;
            }
            set {
                this.partnerErrorCodeField = value;
                this.RaisePropertyChanged("partnerErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.moneygram.com/RealTimeEP")]
    public enum ValidType {
        
        /// <remarks/>
        PASS,
        
        /// <remarks/>
        FAIL,
        
        /// <remarks/>
        ERROR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.moneygram.com/RealTimeEP")]
    public partial class LoadRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string receiveAgentIdField;
        
        private string receiveCodeField;
        
        private string referenceNumberField;
        
        private System.DateTime sendDateField;
        
        private string receiveISOCurrencyField;
        
        private string receiveISOCountryField;
        
        private string receiveAccountNumberField;
        
        private string sendISOCurrencyField;
        
        private string sendISOCountryField;
        
        private System.Nullable<decimal> sendFxRateField;
        
        private bool sendFxRateFieldSpecified;
        
        private System.Nullable<decimal> sendAmountField;
        
        private bool sendAmountFieldSpecified;
        
        private System.Nullable<decimal> feeAmountField;
        
        private bool feeAmountFieldSpecified;
        
        private decimal receiveAmountField;
        
        private string senderFirstNameField;
        
        private string senderMiddleNameField;
        
        private string senderLastNameField;
        
        private string senderAddress1Field;
        
        private string senderAddress2Field;
        
        private string senderCityField;
        
        private string senderStateProvinceField;
        
        private string senderCountryField;
        
        private string senderZipPostalCodeField;
        
        private string senderPhoneNumberField;
        
        private string senderDateOfBirthField;
        
        private string senderPhotoIdTypeField;
        
        private string senderPhotoIdNumberField;
        
        private string senderPhotoIdStateProvinceField;
        
        private string senderPhotoIdCountryField;
        
        private string senderLegalIdTypeField;
        
        private string senderLegalIdNumberField;
        
        private string receiverFirstNameField;
        
        private string receiverMiddleNameField;
        
        private string receiverLastNameField;
        
        private string receiveAccountNumberExpStrField;
        
        private System.Nullable<bool> receiveAccountSwipeField;
        
        private bool receiveAccountSwipeFieldSpecified;
        
        private string purposeOfFundsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string receiveAgentId {
            get {
                return this.receiveAgentIdField;
            }
            set {
                this.receiveAgentIdField = value;
                this.RaisePropertyChanged("receiveAgentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string receiveCode {
            get {
                return this.receiveCodeField;
            }
            set {
                this.receiveCodeField = value;
                this.RaisePropertyChanged("receiveCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string referenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
                this.RaisePropertyChanged("referenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime sendDate {
            get {
                return this.sendDateField;
            }
            set {
                this.sendDateField = value;
                this.RaisePropertyChanged("sendDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string receiveISOCurrency {
            get {
                return this.receiveISOCurrencyField;
            }
            set {
                this.receiveISOCurrencyField = value;
                this.RaisePropertyChanged("receiveISOCurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string receiveISOCountry {
            get {
                return this.receiveISOCountryField;
            }
            set {
                this.receiveISOCountryField = value;
                this.RaisePropertyChanged("receiveISOCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string receiveAccountNumber {
            get {
                return this.receiveAccountNumberField;
            }
            set {
                this.receiveAccountNumberField = value;
                this.RaisePropertyChanged("receiveAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string sendISOCurrency {
            get {
                return this.sendISOCurrencyField;
            }
            set {
                this.sendISOCurrencyField = value;
                this.RaisePropertyChanged("sendISOCurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string sendISOCountry {
            get {
                return this.sendISOCountryField;
            }
            set {
                this.sendISOCountryField = value;
                this.RaisePropertyChanged("sendISOCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<decimal> sendFxRate {
            get {
                return this.sendFxRateField;
            }
            set {
                this.sendFxRateField = value;
                this.RaisePropertyChanged("sendFxRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sendFxRateSpecified {
            get {
                return this.sendFxRateFieldSpecified;
            }
            set {
                this.sendFxRateFieldSpecified = value;
                this.RaisePropertyChanged("sendFxRateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<decimal> sendAmount {
            get {
                return this.sendAmountField;
            }
            set {
                this.sendAmountField = value;
                this.RaisePropertyChanged("sendAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sendAmountSpecified {
            get {
                return this.sendAmountFieldSpecified;
            }
            set {
                this.sendAmountFieldSpecified = value;
                this.RaisePropertyChanged("sendAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<decimal> feeAmount {
            get {
                return this.feeAmountField;
            }
            set {
                this.feeAmountField = value;
                this.RaisePropertyChanged("feeAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool feeAmountSpecified {
            get {
                return this.feeAmountFieldSpecified;
            }
            set {
                this.feeAmountFieldSpecified = value;
                this.RaisePropertyChanged("feeAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal receiveAmount {
            get {
                return this.receiveAmountField;
            }
            set {
                this.receiveAmountField = value;
                this.RaisePropertyChanged("receiveAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string senderFirstName {
            get {
                return this.senderFirstNameField;
            }
            set {
                this.senderFirstNameField = value;
                this.RaisePropertyChanged("senderFirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string senderMiddleName {
            get {
                return this.senderMiddleNameField;
            }
            set {
                this.senderMiddleNameField = value;
                this.RaisePropertyChanged("senderMiddleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string senderLastName {
            get {
                return this.senderLastNameField;
            }
            set {
                this.senderLastNameField = value;
                this.RaisePropertyChanged("senderLastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string senderAddress1 {
            get {
                return this.senderAddress1Field;
            }
            set {
                this.senderAddress1Field = value;
                this.RaisePropertyChanged("senderAddress1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string senderAddress2 {
            get {
                return this.senderAddress2Field;
            }
            set {
                this.senderAddress2Field = value;
                this.RaisePropertyChanged("senderAddress2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string senderCity {
            get {
                return this.senderCityField;
            }
            set {
                this.senderCityField = value;
                this.RaisePropertyChanged("senderCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string senderStateProvince {
            get {
                return this.senderStateProvinceField;
            }
            set {
                this.senderStateProvinceField = value;
                this.RaisePropertyChanged("senderStateProvince");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string senderCountry {
            get {
                return this.senderCountryField;
            }
            set {
                this.senderCountryField = value;
                this.RaisePropertyChanged("senderCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string senderZipPostalCode {
            get {
                return this.senderZipPostalCodeField;
            }
            set {
                this.senderZipPostalCodeField = value;
                this.RaisePropertyChanged("senderZipPostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public string senderPhoneNumber {
            get {
                return this.senderPhoneNumberField;
            }
            set {
                this.senderPhoneNumberField = value;
                this.RaisePropertyChanged("senderPhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public string senderDateOfBirth {
            get {
                return this.senderDateOfBirthField;
            }
            set {
                this.senderDateOfBirthField = value;
                this.RaisePropertyChanged("senderDateOfBirth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public string senderPhotoIdType {
            get {
                return this.senderPhotoIdTypeField;
            }
            set {
                this.senderPhotoIdTypeField = value;
                this.RaisePropertyChanged("senderPhotoIdType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public string senderPhotoIdNumber {
            get {
                return this.senderPhotoIdNumberField;
            }
            set {
                this.senderPhotoIdNumberField = value;
                this.RaisePropertyChanged("senderPhotoIdNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public string senderPhotoIdStateProvince {
            get {
                return this.senderPhotoIdStateProvinceField;
            }
            set {
                this.senderPhotoIdStateProvinceField = value;
                this.RaisePropertyChanged("senderPhotoIdStateProvince");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public string senderPhotoIdCountry {
            get {
                return this.senderPhotoIdCountryField;
            }
            set {
                this.senderPhotoIdCountryField = value;
                this.RaisePropertyChanged("senderPhotoIdCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public string senderLegalIdType {
            get {
                return this.senderLegalIdTypeField;
            }
            set {
                this.senderLegalIdTypeField = value;
                this.RaisePropertyChanged("senderLegalIdType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public string senderLegalIdNumber {
            get {
                return this.senderLegalIdNumberField;
            }
            set {
                this.senderLegalIdNumberField = value;
                this.RaisePropertyChanged("senderLegalIdNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public string receiverFirstName {
            get {
                return this.receiverFirstNameField;
            }
            set {
                this.receiverFirstNameField = value;
                this.RaisePropertyChanged("receiverFirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public string receiverMiddleName {
            get {
                return this.receiverMiddleNameField;
            }
            set {
                this.receiverMiddleNameField = value;
                this.RaisePropertyChanged("receiverMiddleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public string receiverLastName {
            get {
                return this.receiverLastNameField;
            }
            set {
                this.receiverLastNameField = value;
                this.RaisePropertyChanged("receiverLastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public string receiveAccountNumberExpStr {
            get {
                return this.receiveAccountNumberExpStrField;
            }
            set {
                this.receiveAccountNumberExpStrField = value;
                this.RaisePropertyChanged("receiveAccountNumberExpStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=34)]
        public System.Nullable<bool> receiveAccountSwipe {
            get {
                return this.receiveAccountSwipeField;
            }
            set {
                this.receiveAccountSwipeField = value;
                this.RaisePropertyChanged("receiveAccountSwipe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool receiveAccountSwipeSpecified {
            get {
                return this.receiveAccountSwipeFieldSpecified;
            }
            set {
                this.receiveAccountSwipeFieldSpecified = value;
                this.RaisePropertyChanged("receiveAccountSwipeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public string purposeOfFunds {
            get {
                return this.purposeOfFundsField;
            }
            set {
                this.purposeOfFundsField = value;
                this.RaisePropertyChanged("purposeOfFunds");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.moneygram.com/RealTimeEP")]
    public partial class ValidationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ValidType validField;
        
        private string partnerTransactionIDField;
        
        private string mgiErrorCodeField;
        
        private string[] customErrorParamsField;
        
        private string receiptCodeField;
        
        private string[] customReceiptParamsField;
        
        private string partnerErrorCodeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ValidType valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
                this.RaisePropertyChanged("valid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string partnerTransactionID {
            get {
                return this.partnerTransactionIDField;
            }
            set {
                this.partnerTransactionIDField = value;
                this.RaisePropertyChanged("partnerTransactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string mgiErrorCode {
            get {
                return this.mgiErrorCodeField;
            }
            set {
                this.mgiErrorCodeField = value;
                this.RaisePropertyChanged("mgiErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("customErrorParams", IsNullable=true, Order=3)]
        public string[] customErrorParams {
            get {
                return this.customErrorParamsField;
            }
            set {
                this.customErrorParamsField = value;
                this.RaisePropertyChanged("customErrorParams");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string receiptCode {
            get {
                return this.receiptCodeField;
            }
            set {
                this.receiptCodeField = value;
                this.RaisePropertyChanged("receiptCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("customReceiptParams", IsNullable=true, Order=5)]
        public string[] customReceiptParams {
            get {
                return this.customReceiptParamsField;
            }
            set {
                this.customReceiptParamsField = value;
                this.RaisePropertyChanged("customReceiptParams");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string partnerErrorCode {
            get {
                return this.partnerErrorCodeField;
            }
            set {
                this.partnerErrorCodeField = value;
                this.RaisePropertyChanged("partnerErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MGISoapChannel : DevWebApi.MGIWebservice.MGISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MGISoapClient : System.ServiceModel.ClientBase<DevWebApi.MGIWebservice.MGISoap>, DevWebApi.MGIWebservice.MGISoap {
        
        public MGISoapClient() {
        }
        
        public MGISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MGISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MGISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MGISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public DevWebApi.MGIWebservice.ValidationResponse ValidationRequest(DevWebApi.MGIWebservice.ValidationRequest Request) {
            return base.Channel.ValidationRequest(Request);
        }
        
        public System.Threading.Tasks.Task<DevWebApi.MGIWebservice.ValidationResponse> ValidationRequestAsync(DevWebApi.MGIWebservice.ValidationRequest Request) {
            return base.Channel.ValidationRequestAsync(Request);
        }
        
        public DevWebApi.MGIWebservice.LoadResponse LoadRequest(DevWebApi.MGIWebservice.LoadRequest Request) {
            return base.Channel.LoadRequest(Request);
        }
        
        public System.Threading.Tasks.Task<DevWebApi.MGIWebservice.LoadResponse> LoadRequestAsync(DevWebApi.MGIWebservice.LoadRequest Request) {
            return base.Channel.LoadRequestAsync(Request);
        }
    }
}
